[bans]
multiple-versions = "deny"
skip-tree = [
    # We never enable loom in any of our dependencies but it causes dupes
    { name = "loom", version = "0.7.2" },
    { name = "windows-sys", version = "0.45" },
    { name = "winit", version = "0.29" },
    { name = "rustc_version", version = "0.2.3" },
    { name = "miniz_oxide", version = "0.7.4" },

    # introduced by Deno, to be investigated
    { name = "strum_macros", version = "0.25.3" },
    { name = "petgraph", version = "0.6.5" },
    { name = "base64-simd", version = "0.7.0" },
    { name = "bit-set", version = "0.5.3" },
    { name = "bit-vec", version = "0.6.3" },
    { name = "capacity_builder", version = "0.1.3" },
    { name = "itertools", version = "0.10.5" },
]
skip = [
    # Strum uses an old version
    { name = "heck", version = "0.4.0" },
    # Deno uses an old version
    { name = "strum", version = "0.25.0" },
]
wildcards = "deny"
allow-wildcard-paths = true

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MPL-2.0",
    "MIT",
    "MIT-0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
]
private = { ignore = true }

[sources]
allow-git = [
    # Waiting on releases; used in examples only
]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[sources.allow-org]
github = ["gfx-rs"]
