[package]
name = "custom-backend"
edition = "2021"
rust-version = "1.85"
publish = false

[dependencies]
wgpu = { version = "24.0.0", features = ["custom"], default-features = false }
pollster = { version = "0.4", features = ["macro"] }
