[package]
name = "hlsl-snapshots"
version.workspace = true
edition.workspace = true
publish = false
license.workspace = true

[lib]
name = "hlsl_snapshots"
path = "src/lib.rs"
test = false

[dependencies]
anyhow = "1"
nanoserde = "0.2.1"
